FROM nvidia/opengl:1.0-glvnd-runtime-ubuntu18.04

ARG CARLA_VERSION="0.9.8"
ARG HOST_USER

RUN useradd -m -u ${HOST_USER} carla

RUN apt-get update \
    && apt-get install -y tzdata \
    && apt-get install -y software-properties-common \
    && apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 304F9BC29914A77D \
    && add-apt-repository "deb [arch=amd64 trusted=yes] http://dist.carla.org/carla-0.9.8/ all main" \
    && apt-get update \
    && apt-get install -y xdg-user-dirs carla

WORKDIR /opt/carla
RUN /bin/bash ImportAssets.sh

USER ${HOST_USER}
WORKDIR /home/carla
CMD /opt/carla/bin/CarlaUE4.sh
